services:
  postgis:
    image: postgis/postgis:15-3.4
    container_name: postgis
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # ports:
    #   - "${DB_PORT}:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      
  app:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: listrik-app-be
    restart: always
    env_file:
      - .env
    depends_on:
      - postgis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.listrik.rule=Host(`listrik.duitebot.com`)"
      - "traefik.http.routers.listrik.entrypoints=websecure"
      - "traefik.http.routers.listrik.tls.certresolver=cfresolver"
      - "traefik.http.services.listrik.loadbalancer.server.port=3000"

  importer:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: listrik-importer
    restart: always
    command: bun run import
    env_file:
      - .env
    depends_on:
      - postgis
      
volumes:
  postgis_data:
